"""initial: workout_logs and coffee_logs

Revision ID: beb615d53e2c
Revises: 
Create Date: 2026-03-18 21:16:17.569659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'beb615d53e2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bean_name', sa.Text(), nullable=False),
    sa.Column('bean_origin', sa.Text(), nullable=True),
    sa.Column('roast_level', sa.Text(), nullable=True),
    sa.Column('grind_setting', sa.Text(), nullable=True),
    sa.Column('dose_g', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('water_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('water_temp', sa.Integer(), nullable=True),
    sa.Column('brew_time_sec', sa.Integer(), nullable=True),
    sa.Column('brew_method', sa.Text(), nullable=True),
    sa.Column('taste_rating', sa.Integer(), nullable=True),
    sa.Column('taste_notes', sa.Text(), nullable=True),
    sa.Column('bed_photo_path', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('brew_time_sec >= 0', name=op.f('ck_coffee_logs_coffee_logs_brew_time_positive')),
    sa.CheckConstraint('taste_rating >= 1 AND taste_rating <= 5', name=op.f('ck_coffee_logs_coffee_logs_taste_rating_range')),
    sa.CheckConstraint('water_temp >= 0 AND water_temp <= 100', name=op.f('ck_coffee_logs_coffee_logs_water_temp_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coffee_logs'))
    )
    op.create_index(op.f('ix_coffee_logs_date'), 'coffee_logs', ['date'], unique=False)
    op.create_table('workout_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('workout_type', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('wod_program', sa.Text(), nullable=True),
    sa.Column('main_record', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pre_meal', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avg_hr >= 0 AND avg_hr <= 250', name=op.f('ck_workout_logs_workout_logs_avg_hr_range')),
    sa.CheckConstraint('calories >= 0', name=op.f('ck_workout_logs_workout_logs_calories_positive')),
    sa.CheckConstraint('max_hr >= 0 AND max_hr <= 250', name=op.f('ck_workout_logs_workout_logs_max_hr_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_logs'))
    )
    op.create_index(op.f('ix_workout_logs_date'), 'workout_logs', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_logs_date'), table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index(op.f('ix_coffee_logs_date'), table_name='coffee_logs')
    op.drop_table('coffee_logs')
    # ### end Alembic commands ###
